/*______________________________________________________________________
   ¦Autor     ¦ Breno Ferreira                      ¦ Data ¦ 06/08/12 ¦
   +----------+-------------------------------------------------------¦
   ¦Descrição ¦ P.E. para incluir botao na rotina NFSEFAZ             ¦
  ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯*/
#include "rwmake.ch"

user function FISTRFNFE()
	AAdd(aRotina,{"Imprimir CC-e","U_IMPCCE",0,3,0,nil})
return .T.