/*______________________________________________________________________
   ¦Autor     ¦ Breno Ferreira                      ¦ Data ¦ 30/08/14 ¦
   +----------+-------------------------------------------------------¦
   ¦Descrição ¦ PE para adicionar um botão no cadastro da TES         ¦
  ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯*/
#include "rwmake.ch"

user function MA080MNU()
	AAdd(aRotina,{"Copia","U_COPSF4()",0,3,0,nil})
return